spring.application.name=ctav_db

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ctav_db
spring.datasource.username=postgres
spring.datasource.password=@@m159753123R@@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
